
version: '3.3'

services:

  broker:
    image: carlop95/gps-mqtt:1.0
    ports:
        - '1883:1883'
    networks:
        - network

  mmm:
    image: carlop95/3m
    ports:
        - '10203:10203/udp'
    networks:
        - network

  object-storage:
    image: 'minio/minio'

    environment:
      MINIO_ACCESS_KEY: "3M-Gps-Chat"
      MINIO_SECRET_KEY: "MMMmmmMMM"
    command: server /data
    networks:
      - network
      
  im:
    image: carlop95/interaction-manager:1.0
    ports:
        - '5683:5683'
    networks:
        - network

networks:
  network:
