
version: '3.3'

services:

  broker:
    image: carlop95/gps-mqtt:1.0
    ports:
        - '1883:1883'
    networks:
        - network

  mmm:
    image: 'carlop95/3m'
    #ports:
    # Do not expose any ports.
    #    - '10203:10203'
    networks:
        - network

  object-storage:
    image: 'minio/minio'

    #ports:
    # Do not expose any ports
      #- '9000:9000'

    environment:
      MINIO_ACCESS_KEY: "3M-Gps-Chat"
      MINIO_SECRET_KEY: "MMMmmmMMM"
    command: server /data
    networks:
      - network

networks:
  network:
