
version: '3.7'

services:

  broker:
    image: carlop95/gps-mqtt:1.0
    ports:
        - '1883:1883'
    networks:
        - network

  mmm:
    image: carlop95/3m
    #    ports:
            #        - '10203:10203'
    environment:
      3M_MINIO_ACCESS_KEY: "3M-Gps-Chat"
      3M_MINIO_SECRET_KEY: "MMMmmmMMM"
      3M_MINIO_HOST: "object-storage"
      3M_MINIO_PORT: 9000
    networks:
        - network

  object-storage:
    image: 'minio/minio'
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "3M-Gps-Chat"
      MINIO_SECRET_KEY: "MMMmmmMMM"
    command: server /data
    networks:
      - network
      
  im:
    image: carlop95/interaction-manager:1.0
    #    ports:
            #        - '5683:5683/udp'
    networks:
        - network

  gateway:
    image: nginx:alpine
    ports:
      - 80:80
      - 10203:10203
      - 5683:5683/udp
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
networks:
  network:
