# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from models.base_model_ import Model
import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: float=None, message: str=None, id: float=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param code: The code of this InlineResponse200.  # noqa: E501
        :type code: float
        :param message: The message of this InlineResponse200.  # noqa: E501
        :type message: str
        :param id: The id of this InlineResponse200.  # noqa: E501
        :type id: float
        """
        self.swagger_types = {
            'code': float,
            'message': str,
            'id': float
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'id': 'id'
        }
        self._code = code
        self._message = message
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> float:
        """Gets the code of this InlineResponse200.


        :return: The code of this InlineResponse200.
        :rtype: float
        """
        return self._code

    @code.setter
    def code(self, code: float):
        """Sets the code of this InlineResponse200.


        :param code: The code of this InlineResponse200.
        :type code: float
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse200.


        :return: The message of this InlineResponse200.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse200.


        :param message: The message of this InlineResponse200.
        :type message: str
        """

        self._message = message

    @property
    def id(self) -> float:
        """Gets the id of this InlineResponse200.


        :return: The id of this InlineResponse200.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id: float):
        """Sets the id of this InlineResponse200.


        :param id: The id of this InlineResponse200.
        :type id: float
        """

        self._id = id
